# Метод Зейделя

Возьмём систему: ${\displaystyle A{\vec {x}}={\vec {b}}}$, 
 где $ {\displaystyle A=\left({\begin{array}{ccc}a_{11}&\ldots &a_{1n}\\\vdots &\ddots &\vdots \\a_{n1}&\ldots &a_{nn}\end{array}}\right),\quad {\vec {b}}=\left({\begin{array}{c}b_{1}\\\vdots \\b_{n}\end{array}}\right)}\\
$


Итерационный процесс в методе Гаусса — Зейделя строится по формуле

${\displaystyle (\mathrm {L} +\mathrm {D} ){\vec {x}}^{(k+1)}=-\mathrm {U} {\vec {x}}^{(k)}+{\vec {b}},\quad k=0,1,2,\ldots }$

 где в принятых обозначениях ${\displaystyle \mathrm {D} }$ означает матрицу, у которой на главной диагонали стоят соответствующие элементы матрицы ${\displaystyle A}$, а все остальные нули; тогда как матрицы ${\displaystyle \mathrm {U} } $ и ${\displaystyle \mathrm {L} } $ содержат верхнюю и нижнюю треугольные части ${\displaystyle A} $, на главной диагонали которых нули.

In [18]:
import numpy as np

rndm = np.random.RandomState(140)
n = 4
A = rndm.uniform(size=(n, n)) 
b = rndm.uniform(size=n)
print(A)

[[0.74790552 0.10873232 0.00098478 0.29656331]
 [0.0019685  0.32063765 0.09247783 0.59127811]
 [0.19194663 0.91172461 0.88880116 0.48760579]
 [0.27527877 0.10268944 0.09207659 0.85574278]]



Метод будет сходиться, когда все собственные значения матрицы $ L^{-1}U < 1$ по модулю.

In [19]:

x = np.ones(n)
U = np.triu(A, k=1)
L = np.tril(A)
G = np.linalg.inv(L)
n = 20  

def resh(a, t, x):
    G_1 = ( G @ U)
    eigen = np.linalg.eig(G_1)[0]
    if np.fabs(np.max(np.abs(eigen)))<1: 
        print(eig)
        for _ in range(t):
            x = np.dot(G, b - np.dot(U, x))
    else:
            print('расходится')
    return x  

np.allclose(resh(A, n, x), np.linalg.solve(A,b))

[ 0.        +0.j         -0.21383648+0.26284027j -0.21383648-0.26284027j
 -0.06445329+0.j        ]


True